import type { KitModule, ScopedModules } from '../resolvers';
import type { WriteableFile } from '../utils';

import path from 'pathe';

import { namespaces, resolveNuxtModules, resolveVueModules } from '../resolvers';
import { createRuntimeResolver, relativePath } from '../utils';

const generatedFileHeader = `/**
   * This file is auto-generated by @skgn/melkor-kit
   * Don't edit it manually or changes will be overriden on next generation
   */\n\n`;

function generateIndexFile(modules: KitModule[], filePath: string): WriteableFile {
  const dir = path.dirname(filePath);
  let fileContent = generatedFileHeader;
  for (const module of modules) {
    if (module.id === 'index') {
      continue;
    }
    const rPath = relativePath(dir, module.filePath);
    if (module.type === 'sfc') {
      fileContent += `export { default as ${module.name} } from '${rPath}';\n`;
    }
    fileContent += `export * from '${module.type === 'sfc' ? rPath : rPath.replace('.ts', '')}';\n`;
  }
  return {
    content: fileContent,
    filePath,
  };
}

async function _generateIndexFiles(scopedModules: ScopedModules, scopedPath: string) {
  const files = await Promise.all(
    namespaces.map(namespace => generateIndexFile(
      scopedModules[namespace],
      path.resolve(scopedPath, `${namespace}/index.ts`),
    )),
  );

  return files;
}

export async function generateNuxtIndexFiles(cwd: string): Promise<WriteableFile[]> {
  const srcDir = path.resolve(cwd, 'src');
  const runtimeResolver = createRuntimeResolver(srcDir);
  const modules = await resolveNuxtModules(runtimeResolver);
  const files = await _generateIndexFiles(modules, runtimeResolver.nuxtDir);
  return files;
}

export async function generateVueIndexFiles(cwd: string): Promise<WriteableFile[]> {
  const srcDir = path.resolve(cwd, 'src');
  const runtimeResolver = createRuntimeResolver(srcDir);
  const modules = await resolveVueModules(runtimeResolver);
  const files = await _generateIndexFiles(modules, runtimeResolver.vueDir);
  return files;
}

export async function generateIndexFiles(cwd: string): Promise<WriteableFile[]> {
  return (await Promise.all([
    generateVueIndexFiles(cwd),
    generateNuxtIndexFiles(cwd),
  ])).flat(1);
}
