/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const STORAGE_THEME_KEY: typeof import('../../melkor/dist/runtime/vue/features/config.js').STORAGE_THEME_KEY
  const Shape: typeof import('../../melkor/dist/runtime/vue/features/config.js').Shape
  const Theme: typeof import('../../melkor/dist/runtime/vue/features/config.js').Theme
  const bindInteractionStateProps: typeof import('../../melkor/dist/runtime/vue/features/interactions.js').bindInteractionStateProps
  const createGlobalConfig: typeof import('../../melkor/dist/runtime/vue/features/config.js').createGlobalConfig
  const createMelkorOptions: typeof import('../../melkor/dist/runtime/vue/features/config.js').createMelkorOptions
  const durationToNumber: typeof import('../../melkor/dist/runtime/vue/features/style.js').durationToNumber
  const floatingLayerId: typeof import('../../melkor/dist/runtime/vue/features/config.js').floatingLayerId
  const formatErrors: typeof import('../../melkor/dist/runtime/vue/features/utils.js').formatErrors
  const forwardDataAttributes: typeof import('../../melkor/dist/runtime/vue/features/utils.js').forwardDataAttributes
  const getFramework: typeof import('../../melkor/dist/runtime/vue/features/framework.js')['getFramework']
  const getPersistedThemePreference: typeof import('../../melkor/dist/runtime/vue/features/theme.js').getPersistedThemePreference
  const getRuntimeScope: typeof import('../../melkor/dist/runtime/vue/features/runtime-scope.js').getRuntimeScope
  const getSystemColorScheme: typeof import('../../melkor/dist/runtime/vue/features/theme.js').getSystemColorScheme
  const getThemeValue: typeof import('../../melkor/dist/runtime/vue/features/theme.js').getThemeValue
  const globalConfigContextKey: typeof import('../../melkor/dist/runtime/vue/features/config.js').globalConfigContextKey
  const globalIconsContextKey: typeof import('../../melkor/dist/runtime/vue/features/icons.js').globalIconsContextKey
  const globalThemeContextKey: typeof import('../../melkor/dist/runtime/vue/features/theme.js').globalThemeContextKey
  const globalToastContextKey: typeof import('../../melkor/dist/runtime/vue/features/toast.js').globalToastContextKey
  const hasErrors: typeof import('../../melkor/dist/runtime/vue/features/input.js').hasErrors
  const inputDefaultProps: typeof import('../../melkor/dist/runtime/vue/features/input.js').inputDefaultProps
  const isZodError: typeof import('../../melkor/dist/runtime/vue/features/utils.js').isZodError
  const isZodType: typeof import('../../melkor/dist/runtime/vue/features/utils.js').isZodType
  const log: typeof import('../../melkor/dist/runtime/vue/features/internal/logger.js').log
  const mergeConfig: typeof import('../../melkor/dist/runtime/vue/features/config.js').mergeConfig
  const normalizeSlot: typeof import('../../melkor/dist/runtime/vue/features/slots.js').normalizeSlot
  const persistThemePreference: typeof import('../../melkor/dist/runtime/vue/features/theme.js').persistThemePreference
  const remToPixels: typeof import('../../melkor/dist/runtime/vue/features/style.js').remToPixels
  const setElementTheme: typeof import('../../melkor/dist/runtime/vue/features/theme.js').setElementTheme
  const surfaceContextKey: typeof import('../../melkor/dist/runtime/vue/features/surface.js').surfaceContextKey
  const surfaceElevationOrder: typeof import('../../melkor/dist/runtime/vue/features/surface.js').surfaceElevationOrder
  const themeContextKey: typeof import('../../melkor/dist/runtime/vue/features/theme.js').themeContextKey
  const useForm: typeof import('../../melkor/dist/runtime/vue/composables/useForm.js').useForm
  const useFramework: typeof import('../../melkor/dist/runtime/vue/composables/useFramework.js')['useFramework']
  const useGlobalConfig: typeof import('../../melkor/dist/runtime/vue/composables/useGlobalConfig.js').useGlobalConfig
  const useGlobalTheme: typeof import('../../melkor/dist/runtime/vue/composables/useGlobalTheme.js').useGlobalTheme
  const useIconCollection: typeof import('../../melkor/dist/runtime/vue/composables/useIconCollection.js').useIconCollection
  const useInput: typeof import('../../melkor/dist/runtime/vue/composables/useInput.js').useInput
  const useInputBinding: typeof import('../../melkor/dist/runtime/vue/composables/useInputBinding.js').useInputBinding
  const useInputErrors: typeof import('../../melkor/dist/runtime/vue/composables/useInputErrors.js').useInputErrors
  const useNextTheme: typeof import('../../melkor/dist/runtime/vue/composables/useNextTheme.js').useNextTheme
  const usePagination: typeof import('../../melkor/dist/runtime/vue/composables/usePagination.js').usePagination
  const useProvideGlobalTheme: typeof import('../../melkor/dist/runtime/vue/composables/internal/useProvideGlobalTheme.js').useProvideGlobalTheme
  const useProvideIcons: typeof import('../../melkor/dist/runtime/vue/composables/internal/useProvideIcons.js').useProvideIcons
  const useRuntimeScope: typeof import('../../melkor/dist/runtime/vue/composables/useRuntimeScope.js').useRuntimeScope
  const useSurface: typeof import('../../melkor/dist/runtime/vue/composables/useSurface.js').useSurface
  const useTheme: typeof import('../../melkor/dist/runtime/vue/composables/useTheme.js').useTheme
  const useThemes: typeof import('../../melkor/dist/runtime/vue/composables/useThemes.js').useThemes
  const useToast: typeof import('../../melkor/dist/runtime/vue/composables/useToast.js').useToast
  const validateInputValue: typeof import('../../melkor/dist/runtime/vue/features/input.js').validateInputValue
  const warn: typeof import('../../melkor/dist/runtime/vue/features/internal/logger.js').warn
  const watchSystemThemeChange: typeof import('../../melkor/dist/runtime/vue/features/theme.js').watchSystemThemeChange
}
// for type re-export
declare global {
  // @ts-ignore
  export type { UseFormOptions } from '../../melkor/dist/runtime/vue/composables/useForm.d'
  import('../../melkor/dist/runtime/vue/composables/useForm.d')
  // @ts-ignore
  export type { UseIconCollectionOptions } from '../../melkor/dist/runtime/vue/composables/useIconCollection.d'
  import('../../melkor/dist/runtime/vue/composables/useIconCollection.d')
  // @ts-ignore
  export type { UseInputOptions } from '../../melkor/dist/runtime/vue/composables/useInput.d'
  import('../../melkor/dist/runtime/vue/composables/useInput.d')
  // @ts-ignore
  export type { UsePaginationOptions } from '../../melkor/dist/runtime/vue/composables/usePagination.d'
  import('../../melkor/dist/runtime/vue/composables/usePagination.d')
  // @ts-ignore
  export type { UseSurfaceOptions } from '../../melkor/dist/runtime/vue/composables/useSurface.d'
  import('../../melkor/dist/runtime/vue/composables/useSurface.d')
  // @ts-ignore
  export type { CheckableProps } from '../../melkor/dist/runtime/vue/features/checkable.d'
  import('../../melkor/dist/runtime/vue/features/checkable.d')
  // @ts-ignore
  export type { Theme, MelkorOptions, GlobalConfig, Shape } from '../../melkor/dist/runtime/vue/features/config.d'
  import('../../melkor/dist/runtime/vue/features/config.d')
  // @ts-ignore
  export type { IconCollection, IconCollectionName } from '../../melkor/dist/runtime/vue/features/icons.d'
  import('../../melkor/dist/runtime/vue/features/icons.d')
  // @ts-ignore
  export type { InputProps, InputEmits, InputSlots, InputExpose, ValidateInputValue, ValidateInputValueReturn } from '../../melkor/dist/runtime/vue/features/input.d'
  import('../../melkor/dist/runtime/vue/features/input.d')
  // @ts-ignore
  export type { InteractionStateProps, ActiveProps, HoveredProps, DisabledProps, FocusedProps } from '../../melkor/dist/runtime/vue/features/interactions.d'
  import('../../melkor/dist/runtime/vue/features/interactions.d')
  // @ts-ignore
  export type { MaybeSlot, UnwrapSlots } from '../../melkor/dist/runtime/vue/features/slots.d'
  import('../../melkor/dist/runtime/vue/features/slots.d')
  // @ts-ignore
  export type { SurfaceElevation, SurfaceElevationDirection, SurfaceContextInjection } from '../../melkor/dist/runtime/vue/features/surface.d'
  import('../../melkor/dist/runtime/vue/features/surface.d')
  // @ts-ignore
  export type { Themes, SystemTheme, ThemeInstance } from '../../melkor/dist/runtime/vue/features/theme.d'
  import('../../melkor/dist/runtime/vue/features/theme.d')
  // @ts-ignore
  export type { ToastPosition, ToastSwipeDirection, ToastContext } from '../../melkor/dist/runtime/vue/features/toast.d'
  import('../../melkor/dist/runtime/vue/features/toast.d')
  // @ts-ignore
  export type { KeysAs, InferDefaults } from '../../melkor/dist/runtime/vue/features/utils.d'
  import('../../melkor/dist/runtime/vue/features/utils.d')
}
