/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppTypeDemo: typeof import('./src/components/AppTypeDemo.vue')['default']
    MkButton: typeof import('./../../melkor/dist/runtime/vue/components/Button.vue')['default']
    MkRuntimeScope: typeof import('./../../melkor/dist/runtime/vue/components/RuntimeScope.vue')['default']
    MkTheApp: typeof import('./../../melkor/dist/runtime/vue/components/TheApp.vue')['default']
    MkThemeSelector: typeof import('./../../melkor/dist/runtime/vue/components/ThemeSelector.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
