/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MkBuildTester: typeof import('./../../melkor/dist/runtime/vue/components/BuildTester.vue')['default']
    MkButton: typeof import('./../../melkor/dist/runtime/vue/components/Button.vue')['default']
    MkTheApp: typeof import('./../../melkor/dist/runtime/vue/components/TheApp.vue')['default']
    MkThemeSelector: typeof import('./../../melkor/dist/runtime/vue/components/ThemeSelector.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
