import type { InjectionKey } from 'vue';

export type IconCollection = {
  name: IconCollectionName;
  categories: {
    label: string;
    icons: string[];
  }[];
};

export const globalIconsContextKey = Symbol('melkor.icons-global-context') as InjectionKey<{
  loadCollection: (collectionName: IconCollectionName) => Promise<IconCollection>;
}>;

export type IconCollectionName =
  'material-symbols' |
  'material-symbols-light' |
  'ic' |
  'mdi' |
  'mdi-light' |
  'line-md' |
  'solar' |
  'tabler' |
  'mingcute' |
  'ri' |
  'mynaui' |
  'iconamoon' |
  'iconoir' |
  'lucide' |
  'lucide-lab' |
  'uil' |
  'tdesign' |
  'si' |
  'bx' |
  'bxs' |
  'majesticons' |
  'gg' |
  'flowbite' |
  'basil' |
  'pixelarticons' |
  'pixel' |
  'akar-icons' |
  'ci' |
  'proicons' |
  'typcn' |
  'meteor-icons' |
  'prime' |
  'circum' |
  'fe' |
  'eos-icons' |
  'bitcoin-icons' |
  'humbleicons' |
  'uim' |
  'uit' |
  'uis' |
  'gridicons' |
  'mi' |
  'cuida' |
  'weui' |
  'duo-icons' |
  'svg-spinners' |
  'hugeicons' |
  'lets-icons' |
  'streamline-ultimate' |
  'streamline-plump' |
  'streamline-sharp' |
  'mage' |
  'stash' |
  'lineicons' |
  'icon-park-outline' |
  'icon-park-solid' |
  'icon-park-twotone' |
  'jam' |
  'streamline-cyber' |
  'guidance' |
  'carbon' |
  'ion' |
  'famicons' |
  'ant-design' |
  'lsicon' |
  'gravity-ui' |
  'cil' |
  'ep' |
  'charm' |
  'quill' |
  'bytesize' |
  'bi' |
  'streamline-pixel' |
  'streamline-block' |
  'rivet-icons' |
  'nimbus' |
  'formkit' |
  'fluent' |
  'ph' |
  'teenyicons' |
  'clarity' |
  'streamline-freehand' |
  'ix' |
  'octicon' |
  'memory' |
  'system-uicons' |
  'radix-icons' |
  'zondicons' |
  'uiw' |
  'maki' |
  'codex' |
  'ei' |
  'heroicons' |
  'sidekickicons' |
  'pepicons-pop' |
  'pepicons-print' |
  'pepicons-pencil' |
  'f7' |
  'pajamas' |
  'garden' |
  'streamline' |
  'streamline-flex' |
  'fa7-solid' |
  'fa7-regular' |
  'picon' |
  'ooui' |
  'oui' |
  'nrk' |
  'dinkie-icons' |
  'qlementine-icons' |
  'streamline-ultimate-color' |
  'streamline-plump-color' |
  'streamline-freehand-color' |
  'streamline-kameleon-color' |
  'streamline-stickies-color' |
  'fluent-color' |
  'streamline-color' |
  'streamline-flex-color' |
  'streamline-sharp-color' |
  'streamline-cyber-color' |
  'icon-park' |
  'marketeq' |
  'vscode-icons' |
  'codicon' |
  'material-icon-theme' |
  'file-icons' |
  'devicon' |
  'devicon-plain' |
  'catppuccin' |
  'skill-icons' |
  'unjs' |
  'simple-icons' |
  'logos' |
  'streamline-logos' |
  'cib' |
  'fa7-brands' |
  'bxl' |
  'nonicons' |
  'arcticons' |
  'cbi' |
  'brandico' |
  'entypo-social' |
  'token' |
  'token-branded' |
  'cryptocurrency' |
  'cryptocurrency-color' |
  'openmoji' |
  'twemoji' |
  'noto' |
  'fluent-emoji-flat' |
  'fluent-emoji-high-contrast' |
  'noto-v1' |
  'emojione' |
  'emojione-monotone' |
  'emojione-v1' |
  'fxemoji' |
  'streamline-emojis' |
  'circle-flags' |
  'flag' |
  'flagpack' |
  'cif' |
  'gis' |
  'map' |
  'geo' |
  'game-icons' |
  'fad' |
  'academicons' |
  'wi' |
  'meteocons' |
  'healthicons' |
  'medical-icon' |
  'covid' |
  'la' |
  'eva' |
  'dashicons' |
  'flat-color-icons' |
  'entypo' |
  'foundation' |
  'raphael' |
  'icons8' |
  'iwwa' |
  'gala' |
  'heroicons-outline' |
  'heroicons-solid' |
  'fa6-solid' |
  'fa6-regular' |
  'fa6-brands' |
  'fa-solid' |
  'fa-regular' |
  'fa-brands' |
  'fa' |
  'fluent-mdl2' |
  'fontisto' |
  'icomoon-free' |
  'subway' |
  'oi' |
  'wpf' |
  'simple-line-icons' |
  'et' |
  'el' |
  'vaadin' |
  'grommet-icons' |
  'whh' |
  'si-glyph' |
  'zmdi' |
  'ls' |
  'bpmn' |
  'flat-ui' |
  'vs' |
  'topcoat' |
  'il' |
  'websymbol' |
  'fontelico' |
  'ps' |
  'feather' |
  'mono-icons' |
  'pepicons' |
  'fluent-emoji'
;
